// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import { getDatabaseUrl } from "./lib/database-url";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Generation needs only the schema. Database commands still require a URL,
    // and configured connections retain the same TLS validation as runtime.
    url: process.env.DATABASE_URL ? getDatabaseUrl() : undefined,
  },
});
